### ISSUE TITLE
basic-solor-config islandora_transforms now in a git submodule 

### ISSUE THREAD

**Issue by lo5an** [Islandora-Labs/islandora_vagrant_base_box#22]
I'm seeing the following errors on `vagrant up`: 
```
==> default: Installing GSearch
==> default: Cloning into 'basic-solr-config'...
==> default: Switched to a new branch '4.x'
==> default: Branch 4.x set up to track remote branch 4.x from origin.
==> default: sed: can't read ./*xslt: No such file or directory
==> default: Cloning into 'dgi_gsearch_extensions'...
```
when  `gsearch.sh`  does 

```bash
# Dependencies
cd /tmp || exit
git clone https://github.com/discoverygarden/basic-solr-config.git
cd basic-solr-config || exit
git checkout 4.x
cd islandora_transforms || exit
sed -i 's#/usr/local/fedora/tomcat#/var/lib/tomcat7#g' ./*xslt
```
because the `islandora_transforms` code now lives in a submodule at https://github.com/discoverygarden/islandora_transforms. 

It looks like they've specified the url for the submodule as an ssh url, which complicates anonymous access somewhat. 

We could do something like:

```bash
git config --file=.gitmodules submodule.islandora_transforms.url https://github.com/discoverygarden/islandora_transforms.git
git submodule init
git submodule update
```
Thoughts? I haven't really used git submodules, and changing the remote feels a bit weird, but I can't think of a reason that it would break things.

**Comment by lutaylor** [comment]
Should be fixed here 

https://github.com/Islandora-Labs/islandora_vagrant_base_box/pull/23

Had to put some additional pulls in so that it will work with https

**Comment by DonRichards** [comment]
#23 Merged
