### ISSUE TITLE
Base Box Update has an error

### ISSUE THREAD

**Issue by DonRichards** [Islandora-Labs/islandora_vagrant_base_box#30]
The following error happens upon vagrant up. 

```terminal
$ vagrant up
...
...
...
    default: Running: /var/folders/ff/ykfbh8bs7j7cwtp67k7k1h280000gn/T/vagrant-shell20170921-92903-upedbw.sh
==> default: Installing FITS
==> default: chown: invalid user: ‘vagrant:vagrant’
==> default: /tmp/vagrant-shell: line 23: unzip: command not found
==> default: /tmp/vagrant-shell: line 24: cd: /usr/local/fits/fits-1.1.1: No such file or directory
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

**Comment by DonRichards** [comment]
Did a box update and vagrant destroy and still getting the following errors. 

```terminal
$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["list", "hostonlyifs"]

Stderr: VBoxManage: error: Failed to create the VirtualBox object!
VBoxManage: error: Code NS_ERROR_ABORT (0x80004004) - Operation aborted (extended info not available)
VBoxManage: error: Most likely, the VirtualBox COM server is not running or failed to start.
```

**Comment by lutaylor** [comment]
@DonRichards 
I think this might be a bug with either Vagrant or Virtualbox. Can you try updating both applications?

**Comment by DonRichards** [comment]
I've tried this on a couple of machines and I'm getting the same error.

**Comment by pc37utn** [comment]
might be a vbox or vagrant problem, I just did a clean clone and vagrant up on the base box with no errors.

**Comment by bondjimbond** [comment]
As did others - ran a box update (Mac OSX, no VBox update) and no problems.

**Comment by lutaylor** [comment]
I am also on MacOSX.

**Comment by DiegoPino** [comment]
@DonRichards as described here https://forums.virtualbox.org/viewtopic.php?f=8&t=65477 it could be disk permissions. I assume you are also on OSX. Give the repair disk permissions thing/ VirtualBox uninstall /reinstall as second option / a try

**Comment by DonRichards** [comment]
@DiegoPino Just pasting exactly what I have. Clean directory with the latest versions. 

```terminal
$ vagrant --version
Vagrant 2.0.0

$ vboxmanage --version
5.1.28r117968

$ git log -1
commit af2984c9aa0c1c3e553959e92eb021e7fb3e0e67 (HEAD -> master, origin/master, origin/HEAD)
Author: lutaylor <luke@discoverygarden.ca>
Date:   Thu Aug 10 10:51:58 2017 -0300
    Issue 28 (#29)
    * issue-28 details in PR
    * Updating FITS 1.1.1
    * Responding to Diego's feedback.

$ git status
On branch master
Your branch is up-to-date with 'origin/master'.

nothing to commit, working tree clean
```

**Comment by lutaylor** [comment]
@DonRichards @DiegoPino 
Did fresh updates. I am still unable to replicate issue.


```
$ vagrant --version
Vagrant 2.0.0
$ vboxmanage --version
5.1.28r117968
$ git log -1
commit af2984c9aa0c1c3e553959e92eb021e7fb3e0e67
Author: lutaylor <luke@discoverygarden.ca>
Date:   Thu Aug 10 10:51:58 2017 -0300

    Issue 28 (#29)

    * issue-28 details in PR

    * Updating FITS 1.1.1
```

**Comment by DonRichards** [comment]
Something not comment. I use vagrant during most of my day. I have it running a variation of Islandora_vagrant current up and running with no issue. I turn that one off and try this one and I get that error. I'm failing to see how vagrant virtualbox has an issue.

**Comment by DiegoPino** [comment]
@DonRichards will give it a try with your versions. Permission issues could be just for that vm, virtualbox keeps a file registry/cache around. Still will try to find some time to test with your versions and see how that goes and will write you back here on monday. I have 22 different VMs here, so in the same scenario than you, but no issues yet.

**Comment by DonRichards** [comment]
I'm sorry. I intended to close this back in September. This could not be replicated by anyone but me.
